<a href="https://colab.research.google.com/github/kembanggulaa/Sentiment-Analysis-Twitter/blob/cobaan/Permodelan_dan_Klasifikasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
import string
import re

In [ ]:
data_bersih = pd.read_csv("data_preprocessing.csv", encoding = 'utf-8')
data_bersih

Tweet  ...                                      Preprocessing
0    upah ditiadakan maklum pemerintah butuh duit b...  ...  upah tiada maklum perintah butuh duit banyak b...
1    februari pertama kali kerja kantor berlokasi j...  ...  februari pertama kali kerja kantor lokasi jaka...
2    ibukota negara baru didorong pemerataan ekonom...  ...  ibukota negara baru dorong perata ekonomi nasi...
3    undang undang ibukota negara baru resmi disahk...  ...  undang undang ibukota negara baru resmi sah ta...
4    ibukota negara baru demi transformasi pembangu...  ...  ibukota negara baru transformasi bangun buni p...
..                                                 ...  ...                                                ...
712    fess bagus kalo proyek ibukota baru mulai jalan  ...    fess bagus kalo proyek ibukota baru mulai jalan
713  bawah boleh pake misal nkri bubar bang ibukota...  ...  bawah pake misal nkri bubar bang ibukota manta...
714  loren alasan benar lari dari kenyataan alias k...  ...  loren alas benar lari nyata alias kalau maling...
715  partai selingkuh ibukota urus dulu kader parta...  ...  partai selingkuh ibukota urus dulu kader parta...
716  lagi gencar cari dana buat ibukota baru bedany...  ...       gencar cari dana buat ibukota baru beda sama

[717 rows x 3 columns]

In [ ]:
data_bersih = data_bersih.astype({'Hasil' : 'category'})
data_bersih = data_bersih.astype({'Preprocessing' : 'string'})
data_bersih.dtypes

Tweet              object
Hasil            category
Preprocessing      string
dtype: object

In [ ]:
#Mendefinisikan X dan y
X = data_bersih['Preprocessing']
y = data_bersih['Hasil']

In [ ]:
#Split Dataset menggunakan perbandingan 80:20
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, shuffle=True)
X_train.shape, X_test.shape, y_train.shape,y_test.shape

((573,), (144,), (573,), (144,))

In [ ]:
#Proses TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.feature_extraction.text import TfidfTransformer

tf_idf = TfidfVectorizer(max_features=5000)
tf_idf.fit(X)
X_tf_idf = tf_idf.transform(X)
Train_X_tf_idf = tf_idf.transform(X_train)
Test_X_tf_idf = tf_idf.transform(X_test)

print(tf_idf.vocabulary_)

{'upah': 2283, 'tiada': 2191, 'maklum': 1235, 'perintah': 1661, 'butuh': 379, 'duit': 559, 'banyak': 212, 'buat': 348, 'bangun': 205, 'ibukota': 781, 'baru': 219, 'februari': 611, 'pertama': 1667, 'kali': 952, 'kerja': 1031, 'kantor': 971, 'lokasi': 1205, 'jakarta': 861, 'pindah': 1691, 'comfort': 440, 'zone': 2362, 'bandung': 194, 'nyata': 1519, 'beri': 270, 'peluang': 1638, 'sempat': 1952, 'kembang': 1014, 'knowledge': 1069, 'skill': 2016, 'experience': 600, 'bagai': 168, 'bidang': 295, 'negara': 1422, 'dorong': 552, 'perata': 1652, 'ekonomi': 575, 'nasional': 1415, 'nusantara': 1513, 'satu': 1900, 'indonesia': 814, 'undang': 2276, 'resmi': 1841, 'sah': 1871, 'tanda': 2120, 'mula': 1369, 'transformasi': 2222, 'buni': 371, 'pancasila': 1587, 'urgensi': 2287, 'solusi': 2031, 'baik': 179, 'atas': 150, 'soal': 2023, 'nkri': 1499, 'peran': 1649, 'gagal': 634, 'rakyat': 1805, 'sulit': 2071, 'cuma': 453, 'mudah': 1366, 'belanja': 249, 'stok': 2054, 'barang': 217, 'sirkuit': 2005, 'mandalika

In [ ]:
print(y_test)

120    1
331    1
39     0
636    1
514    1
      ..
132    1
292    1
41     1
108    1
264    1
Name: Hasil, Length: 144, dtype: category
Categories (3, int64): [-1, 0, 1]


In [ ]:
#Performa Algoritma KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=18, metric="euclidean")

In [ ]:
#K-fold Cross Validation
from sklearn.model_selection import cross_val_score
valid = cross_val_score(estimator = knn , X = X_tf_idf, y=y , cv=10)
print("Cross Validation results for 10 folds")
print(valid)
print(f"Mean for cross val is {valid.mean()}")
print(f"std for the cross val is {valid.std()}")

Cross Validation results for 10 folds
[0.88888889 0.88888889 0.875      0.875      0.875      0.875
 0.875      0.88732394 0.88732394 0.88732394]
Mean for cross val is 0.8814749608763692
std for the cross val is 0.006497615314721509


In [ ]:
#Training Data
klasifikasi = knn.fit(Train_X_tf_idf, y_train)

#Predict Data
prediksi = klasifikasi.predict(Test_X_tf_idf)

In [ ]:
#Akurasi, Presisi, Recall
from sklearn.metrics import classification_report , accuracy_score , confusion_matrix

print(f"Classification Repport\n  {classification_report(y_test , prediksi)}")

print("\n\n")
print(f"Confudion Matrix  \n {confusion_matrix(y_test , prediksi)}")

print("\n\n")
print(f"Accuracy score   {accuracy_score(y_test , prediksi)}")

Classification Repport
                precision    recall  f1-score   support

          -1       0.00      0.00      0.00         9
           0       0.00      0.00      0.00         1
           1       0.93      1.00      0.96       134

    accuracy                           0.93       144
   macro avg       0.31      0.33      0.32       144
weighted avg       0.87      0.93      0.90       144




Confudion Matrix  
 [[  0   0   9]
 [  0   0   1]
 [  0   0 134]]



Accuracy score   0.9305555555555556


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
